# Generated by Django 5.0 on 2024-01-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_order_paid_order_payment_id_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
